# Use ubuntu as base Docker Image
FROM ubuntu

# OCI Labels
LABEL org.opencontainers.image.authors="Ariful Islam"
LABEL org.opencontainers.image.title="ENTRYPOINT Instruction in Docker"
LABEL org.opencontainers.image.description="Illustrating the use of the ENTRYPOINT instruction"
LABEL org.opencontainers.image.version="1.0"

# Always run the echo command as the entrypoint
ENTRYPOINT ["echo", "Ariful"]